## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('aodvDbscan',
                                 ['wifi', 'internet', 'aodvDbscan', 'internet-apps'])
    obj.source = 'aodvDbscan.cc'
